```{r}
library(ghpm)
library(tidyverse)
library(purrr)
library(tibble)
```
```{r}
data <- graphql_query("issues.graphql", org = "metrumresearchgroup", repo = "pkgr")$repository$issues$nodes

issues <- reduce(data, function(.acc, .cv){
	.acc <- .acc %>% add_row("Title" = .cv$title, "Body" = .cv$bodyText, "Author" = .cv$author$login, "Number" = .cv$number, "Labels" = ifelse(!is_empty(.cv$labels$nodes), .cv$labels$nodes[[1]]$name, NA), "Milestone" = ifelse(is.null(.cv$milestone), "None", .cv$milestone), "State" = .cv$state)
	
	return(.acc)
}, .init = tibble("Title" = NA, "Body" = NA, "Author" = NA, "Number" = NA, "Labels" = NA, "Milestone" = NA, "State" = NA))

milestones = get_milestones("metrumresearchgroup", "pkgr")

# This doesn't work and I don't know how to fix it :( 
milestones <- milestones %>% rename(Milestone = Title)
left_join(milestones, issues, by = "Milestone")

a <- tibble(Col1 = 4, Col2 = 3, Col3 = 2)
bind_rows(a, tibble("Col1" = 1, "Col2" = 2, "Col3" = 3))
```

```{r}
proj_data <- graphql_query("projects.graphql", org = "metrumresearchgroup", repo = "pkgr")$repository$projects$nodes

map_df(proj_data, function(x){
	result <- reduce(x$columns$nodes, function(.acc, .cv){
		column <- .cv$name
		if(length(.cv$cards$nodes)){
			rows <- reduce(.cv$cards$nodes, function(.acc2, .cv2){
				if(!is.null(.cv2$content) && length(.cv2$content) > 0){
					.acc2 <- .acc2 %>% bind_rows(tibble("Number" = .cv2$content$number, "Title" = .cv2$content$title))
				}
				return(.acc2)
			}, .init = tibble(Number = numeric(), Title = character()))
			if (nrow(rows)) {
				.acc <- .acc %>% bind_rows(rows %>% mutate("Column" = column))
			}
		}
		return(.acc)
	}, .init = tibble(Number = numeric(), Title = character(), Column = character(), .rows = 0))
	return(result %>% mutate(board = x$name))
})
```

